module.exports = [
  { name: "JavaScript" },
  { name: "TypeScript" },
  { name: "Java" },
  { name: "C" },
  { name: "Python" },
  { name: "C++" },
  { name: ".NET" },
  { name: "C#" },
  { name: "PHP" },
  { name: "SQL" },
  { name: "Scheme" },
  { name: "Erlang" },
  { name: "Elixir" },
  { name: "Haskell" },
  { name: "Objective-C" },
  { name: "Ruby" },
  { name: "MATLAB" },
  { name: "Assembly language" },
  { name: "Swift" },
  { name: "Go" },
  { name: "Perl" },
  { name: "R" },
  { name: "Scala" },
  { name: "Cobol" },
  { name: "Rust" },
  { name: "CSS" },
  { name: "SASS" },
  { name: "HTML" },
  { name: "XML" },
  { name: "Dart" },
  { name: "Kotlin" },
  { name: "AWS" },
  { name: "Azure" },
  { name: "Google Cloud" },
  { name: "IBM Cloud" },
  { name: "Oracle Cloud" },
  { name: "Firebase" },
  { name: "Oracle" },
  { name: "MongoDB" },
  { name: "Redis" },
  { name: "MySQL" },
  { name: "PostgreSQL" },
  { name: "SQLite" },
  { name: "MariaDB" },
  { name: "Elasticsearch" },
  { name: "DynamoDB" },
  { name: "React" },
  { name: "Vue" },
  { name: "Angular" },
  { name: "Svelte" },
  { name: "Ember" },
];
